In [2]:
# Python Interview Topics:
# Datatypes
# Lists, Arrays, Dictionaries and Tuples
# Slicing
# Lambda functions
# Numpy 
# Multithreading
# Decorators

In [3]:
calc = lambda num:"even" if num%2 ==0 else "odd"
print(calc(3))

filter_num = lambda s: ''.join([ch for ch in s if not ch.isdigit()])
print(filter_num("renu05"))

ex = lambda s: s+'!'
print(ex("hey"),s,"sucess")



l = ["1", "2", "9", "0", "-1", "-2"]
print(sorted(l, key = lambda x: int(x),reverse = True))

sq = lambda x: x*x
print(sq(2))

add = lambda x,y : x+y
print(add(7,8))

odd
renu


NameError: name 's' is not defined

In [ ]:

#filter, map, reduce
from functools import reduce

l=[1,2,3,4,3,4,3,5,3,2,4,2,3]
fil = list(filter(lambda x: x%2==0,l))
print("x: ",fil)
maps = list(map(lambda x: x+2, fil))
print("Map: ", maps)
red = reduce(lambda x,y: x+y,maps)
print("red: ", red)

x:  [2, 4, 4, 2, 4, 2]
Map:  [4, 6, 6, 4, 6, 4]
red:  30


In [ ]:
#decorators : adding extra features to the existing function

def div(a,b):
    return a/b

def smart_div(fun):
    
    def inner(a,b):
        if a<b :
            a,b = b,a
        return fun(a,b)
    return inner


div = smart_div(div)
div(2,6)

3.0

In [ ]:
#threads = break down big process into small process

from threading import *
from time import sleep

class Hello(Thread):
    def run(self):
        for i in range(5):
            print("hello")
            sleep(1)
            
class Hi(Thread):
    def run(self):
        for i in range(5):
            print("hi")
            sleep(1)
            
            
t1 = Hello()
t2 = Hi()

t1.start()
sleep(0.2)
t2.start()

t1.join()
t2.join()

print("bye")

hello
hi
hello
hi
hello
hi
hello
hi
hello
hi
bye


In [ ]:
from array import *

x = array('i',[1,4,3,23,90])
y=array(x.typecode,(a for a in x))
print(y)

array('i', [1, 4, 3, 23, 90])


In [ ]:
from numpy import *

#six ways to create array : array, linespace,logspace,arrange,zeros,ones
a1=array([1,2,3,4,5])
a2=array([2,3,4,5.0])
print(a1, end='')
print(a1.dtype)
print(a2, end='')
print(a2.dtype)


a3=linspace(0,15,17) #start,end(included),no.of.parts to be divided
print(a3)
print(len(a3))

a4=arange(1,10,2) #start, end(inc), step
print(a4)

a5 = logspace(1,40,5) # start 10^1, end at 10^40,divide  into 5 parts
print(a5)
print(a5[2])
print('%.2f' %a5[2]) #value differentiated with log value

a6 = zeros(10,int) #return float by default
print(a6)

a7 = ones(10,int) #return float by default
print(a7)

x = lambda x: x+5
print(x(a7))

y = a7+5
print(y)


a8 = a6+a7
print(a8)
print(sin(a8))
print(sqrt(y)) # min, max, sum, sort, unique
print(concatenate([a6,a7]))


print(id(a6)) #printing the address of the array
a9=a6
a10=a6.view()
a11 = a6.copy()
print(id(a9)) #same address of a6 as alias is created
print(id(a10))
print(id(a11))

a6[2]=1
print(a9) #shallow copy = change made in both array
print(a11) #deep copy as change in a6 wont affect a11

[1 2 3 4 5]int32
[2. 3. 4. 5.]float64
[ 0.      0.9375  1.875   2.8125  3.75    4.6875  5.625   6.5625  7.5
  8.4375  9.375  10.3125 11.25   12.1875 13.125  14.0625 15.    ]
17
[1 3 5 7 9]
[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]
3.1622776601683794e+20
316227766016837943296.00
[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[6 6 6 6 6 6 6 6 6 6]
[6 6 6 6 6 6 6 6 6 6]
[1 1 1 1 1 1 1 1 1 1]
[0.84147098 0.84147098 0.84147098 0.84147098 0.84147098 0.84147098
 0.84147098 0.84147098 0.84147098 0.84147098]
[2.44948974 2.44948974 2.44948974 2.44948974 2.44948974 2.44948974
 2.44948974 2.44948974 2.44948974 2.44948974]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
2301573650768
2301573650768
2301566036624
2301573261104
[0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#numpy with multi dimension array

a1 = array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [1,2,3],
    [4,5,6],
    [7,8,9]
    
    
])

print(a1)
print(a1.ndim)
print(a1.shape)
print(a1.size)

a2 = a1.flatten()
print(a2)

a3 = a2.reshape(2,3,3)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
2
(6, 3)
18
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]


ValueError: cannot reshape array of size 18 into shape (3,3,3)

In [ ]:
# matrix
# nothing diff than array but has more inbuilt operations
#a4 = matrix(a3)
m = matrix(' 1 2 3 4 5; 1 2 3 4 5;1 2 3 4 5;1 2 3 4 5;1 2 3 4 5')
print(m)
print(diagonal(m))

print(m.min()) #max

m1 = matrix(' 1 2 3 4 5; 1 2 3 4 5;1 2 3 4 5;1 2 3 4 5;1 2 3 4 5')
m2 = m1* m 
print(m2)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[1 2 3 4 5]
1
[[15 30 45 60 75]
 [15 30 45 60 75]
 [15 30 45 60 75]
 [15 30 45 60 75]
 [15 30 45 60 75]]
