In [1]:
import numpy as np


In [8]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
b = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((arr,b))

array([2, 1, 5, 3, 7, 4, 6, 8, 5, 6, 7, 8])

In [15]:
#You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
a2 = a[np.newaxis, :]
print(a2.shape)
b = np.expand_dims(a, axis=1)
print(b.shape)
c = np.expand_dims(a, axis=0)
print(c.shape)

(6,)
(1, 6)
(6, 1)
(1, 6)


In [21]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])
five_up = (a >= 5)
print(a[five_up])
not_there = np.nonzero(a == 42)
print(not_there)
five_up = (a > 5) | (a == 5)
print(five_up)
b = np.nonzero(a < 5)
print(b)
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)
print(a[b])

[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
(array([], dtype=int64), array([], dtype=int64))
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [ ]:
#create an array from existing data
#slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [24]:
#unique ele
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[11 12 13 14 15 16 17 18 19 20]
[3 2 2 2 1 1 1 1 1 1]


In [26]:
#reverse array
print(a)
print(np.flip(a))

[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
[20 19 18 14 11 13 12 17 16 15 14 13 12 11 11]


In [ ]:
#There are two popular ways to flatten an array: .flatten() and .ravel(). 
#any changes to the new array will affect the parent array as well. Since ravel does not create a copy, it’s memory efficient.
#When you use flatten, changes to your new array won’t change the parent array.
