In [40]:
import numpy as np
import sys

In [29]:
a1 = arange(15).reshape(3,5)
print(a1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [9]:
#broadcasting:  ability of numpy to perform arithmetic operations between arrays of differenct sizes

a1 = a1 +5 
print(a1)

a2 = arange(5)
print(a2)

print(a1+a2)

a3 = arange(3)
a4 = arange(3).reshape(3,1)
print(a3+a4) # here both the arrays has been broadcasted

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
[0 1 2 3 4]
[[20 22 24 26 28]
 [25 27 29 31 33]
 [30 32 34 36 38]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [19]:
#NumPy dimensions are called axes.
print(a4.ndim)
print(a4.shape)
print(a4.size)
print(a4.dtype)
print(a4.dtype.itemsize)
print(a4.data)

2
(3, 1)
3
int32
4


In [33]:
#array creation
a = array([1,2,3])
print(a)
a = array([(1,2,3),(1,2,3)])
print(a)

a=zeros(5,int)
print(a)
a=ones(5,int)
print(a)

a=empty(5)
print(a)

a= arange(1,12,3)
print(a)

a=linspace(0,13,13)
print(a)

[1 2 3]
[[1 2 3]
 [1 2 3]]
[0 0 0 0 0]
[1 1 1 1 1]
[0. 0. 0. 0. 0.]
[ 1  4  7 10]
[ 0.          1.08333333  2.16666667  3.25        4.33333333  5.41666667
  6.5         7.58333333  8.66666667  9.75       10.83333333 11.91666667
 13.        ]


In [60]:
#printing array
np.set_printoptions(threshold = sys.maxsize)

a=arange(100).reshape(10,10)
#print(a)

print(np.random.rand(2,3))

print(a.sum())
print(a.min())
print(a.max())

print(a.sum(axis=0)) #column wise
print(a.sum(axis=1)) #row wise
print(a.cumsum(axis=1))

def f(x, y):
    return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=int)
print(b)
print(b[0:5,0])
print(b[-1])

for i in b:
    print(i)
    
for i in b.flat:
    print(i)


[[0.79838117 0.63474553 0.03658697]
 [0.07276364 0.27192315 0.29698773]]
4950
0
99
[450 460 470 480 490 500 510 520 530 540]
[ 45 145 245 345 445 545 645 745 845 945]
[[  0   1   3   6  10  15  21  28  36  45]
 [ 10  21  33  46  60  75  91 108 126 145]
 [ 20  41  63  86 110 135 161 188 216 245]
 [ 30  61  93 126 160 195 231 268 306 345]
 [ 40  81 123 166 210 255 301 348 396 445]
 [ 50 101 153 206 260 315 371 428 486 545]
 [ 60 121 183 246 310 375 441 508 576 645]
 [ 70 141 213 286 360 435 511 588 666 745]
 [ 80 161 243 326 410 495 581 668 756 845]
 [ 90 181 273 366 460 555 651 748 846 945]]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
[ 0 10 20 30 40]
[40 41 42 43]
[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [69]:
#shape manipulation
a=random.rand(2,3)
print(a)

#these 3 doesn't change original array
print(a.ravel()) #flattens
print(a.reshape(3,2)) #reshapes
print()
print(a.T) #transpose

#change original array
a.resize((1,6))
a

[[0.96769746 0.39717459 0.42456749]
 [0.57975687 0.05371055 0.03105755]]
[0.96769746 0.39717459 0.42456749 0.57975687 0.05371055 0.03105755]
[[0.96769746 0.39717459]
 [0.42456749 0.57975687]
 [0.05371055 0.03105755]]

[[0.96769746 0.57975687]
 [0.39717459 0.05371055]
 [0.42456749 0.03105755]]


array([[0.96769746, 0.39717459, 0.42456749, 0.57975687, 0.05371055,
        0.03105755]])

In [80]:
#stacking together different arrays
a=random.rand(2,3)
b=random.rand(2,3)
print(np.hstack((a,b)))
print(np.vstack((a,b)))

print(np.r_[1:4,0,4])
print(np.c_[np.array([1,2,3]), np.array([4,5,6])])

[[0.47546397 0.20391773 0.31536311 0.91210919 0.89832311 0.25052101]
 [0.74801482 0.05008206 0.64089488 0.56230425 0.91456782 0.69667291]]
[[0.47546397 0.20391773 0.31536311]
 [0.74801482 0.05008206 0.64089488]
 [0.91210919 0.89832311 0.25052101]
 [0.56230425 0.91456782 0.69667291]]
[1 2 3 0 4]
[[1 4]
 [2 5]
 [3 6]]


In [86]:
#split
a=random.rand(2,12)
#a

#np.hsplit(a,3)
np.hsplit(a, (3, 4))

[array([[0.05000788, 0.16861315, 0.88320526],
        [0.09394994, 0.34992352, 0.22172508]]),
 array([[0.35972131],
        [0.42779599]]),
 array([[0.94144822, 0.05019934, 0.02149445, 0.9030481 , 0.45087506,
         0.91676528, 0.1682922 , 0.6596495 ],
        [0.58455203, 0.96346381, 0.83163425, 0.17770897, 0.37742064,
         0.23297687, 0.08446954, 0.87689609]])]

In [107]:
#copies and views
a=random.rand(2,12)
print('a: ',a)
b=a
print(a.size)
print(id(a),id(b)) #no cpoy at all as python passes mutable objects as refernces


#shallow copy - different address still data changes when changed in one
c=a.view()
print(id(c),id(a))
c.flags.owndata
c.base is a
c[0,4]=1234
print(a)
#slicing
s=a[:,1:3]
print(s)
s[:] = 10
print(a.size)
print(a.shape)


#deep copy
d=a.copy()
d[0,0]=1000
print(d)
print(a)

a:  [[0.52096477 0.48153844 0.21243747 0.83771278 0.34669501 0.89193872
  0.21274257 0.69756504 0.31544713 0.76462852 0.57841589 0.97221824]
 [0.35897569 0.34223398 0.34445083 0.61232676 0.19544319 0.85100236
  0.05089238 0.93690377 0.82358389 0.64779429 0.05016972 0.91059181]]
24
1534992519728 1534992519728
1534995377744 1534992519728
[[5.20964767e-01 4.81538439e-01 2.12437474e-01 8.37712784e-01
  1.23400000e+03 8.91938719e-01 2.12742567e-01 6.97565039e-01
  3.15447127e-01 7.64628519e-01 5.78415891e-01 9.72218242e-01]
 [3.58975690e-01 3.42233980e-01 3.44450826e-01 6.12326764e-01
  1.95443186e-01 8.51002361e-01 5.08923821e-02 9.36903771e-01
  8.23583888e-01 6.47794292e-01 5.01697245e-02 9.10591811e-01]]
[[0.48153844 0.21243747]
 [0.34223398 0.34445083]]
24
(2, 12)
[[1.00000000e+03 1.00000000e+01 1.00000000e+01 8.37712784e-01
  1.23400000e+03 8.91938719e-01 2.12742567e-01 6.97565039e-01
  3.15447127e-01 7.64628519e-01 5.78415891e-01 9.72218242e-01]
 [3.58975690e-01 1.00000000e+01 1.0000